version: "3.8"

services:
  # PostgreSQL
  postgresql_1_postgres:
    image: postgres:latest
    container_name: postgresql_1_postgres
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # - POSTGRES_PASSWORD_FILE: ./data/postgres/secrets/pg_password_file <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
    networks:
      - postgres
      
  # pdAdmin
  postgresql_1_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: postgresql_1_pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgresql_1_postgres
    networks:
      - postgres

  # pgweb
  postgresql_1_pgweb:
    image: sosedoff/pgweb:latest
    container_name: postgresql_1_pgweb
    restart: unless-stopped
    ports: 
      - ${PGWEB_PORT}:8081
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql_1_postgres:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - postgresql_1_postgres
    networks:
      - postgres

  # postgres-backup-local
  postgresql_1_pgbackups:
    image: prodrigestivill/postgres-backup-local:latest
    container_name: postgresql_1_pgbackups
    restart: on-failure
    user: postgres:postgres
    volumes:
      - ./data/pgbackups/backups:/backups
    links:
      - postgresql_1_postgres
    depends_on:
      - postgresql_1_postgres
    environment:
      POSTGRES_HOST: postgresql_1_postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # - POSTGRES_PASSWORD_FILE: ./data/postgres/secrets/pg_password_file <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
      POSTGRES_EXTRA_OPTS: -Z6 --schema=public --blobs
      SCHEDULE: "@midnight"
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
      HEALTHCHECK_PORT: ${PGBACKUPS_PORT}
    depends_on:
      - postgresql_1_postgres
    networks:
      - postgres
      
networks:
  postgres:
    driver: bridge