version: "3.8"

services:
  # Node App 1
  ip2location_mysql_1:
    image: ip2location/mysql:latest
    container_name: ip2location_mysql_1
    restart: unless-stopped
    ports:
      - ${IP2LOCATION_1_PORT}:3306
    environment:
      TOKEN: ${IP2LOCATION_TOKEN}
      CODE: ${IP2LOCATION_CODE}
      IP_TYPE: ${IP2LOCATION_IP_TYPE}
      MYSQL_PASSWORD: ${IP2LOCATION_MYSQL_PASSWORD}
    networks:
      - mysql_net
    command: graphjin serve

networks:
  mysql_net:
    driver: bridge
