version: "3.8"

services:
  # Laravel App 1
  laravel_app_1:
    image: serversideup/php:8.1-fpm-apache
    container_name: laravel_app_1
    restart: unless-stopped
    ports:
      - ${LARAVEL_APP_1_PORT}:80
    volumes:
      - ./project:/var/www/html
    environment:
      RUN_LARAVEL_AUTOMATIONS: "true"
    command: php -S laravel_app_1:9001 -t ./public
    networks:
      - mysql_net

  # Laravel App 2
  laravel_app_2:
    image: serversideup/php:8.1-fpm-nginx
    container_name: laravel_app_2
    restart: unless-stopped
    ports:
      - ${LARAVEL_APP_2_PORT}:80
    volumes:
      - ./project:/var/www/html
    environment:
      RUN_LARAVEL_AUTOMATIONS: "true"
    command: php -S laravel_app_2:9001 -t ./public
    networks:
      - mysql_net

  # MySQL
  mysql_1_db:
    image: mysql:latest
    container_name: mysql_1_db
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - mysql_net

networks:
  mysql_net:
    driver: bridge
