version: "3.8"

services:
  # Laravel App 1
  laravel_app_x:
    build:
      context: ./project
    container_name: laravel_app_x
    restart: unless-stopped
    ports:
      - ${LARAVEL_APP_X_PORT}:80
    volumes:
      - ./project:/var/www/html
    environment:
      RUN_LARAVEL_AUTOMATIONS: "true"
    command: php -S laravel_app_x:9001 -t ./public
    # networks:
    #   - mysql_net

  laravel-redis:
    image: redis:alpine
    container_name: laravel_redis
    # hostname: website_redis
    restart: always
    ports:
      - ${LARAVEL_REDIS_POST}:6379
    # networks:
    #   - reverse-proxy
