version: "3.8"

services:
  # Prometheus
  prometheus_1:
    image: prom/prometheus:latest
    container_name: prometheus_1
    restart: unless-stopped
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./prometheus/conf/:/etc/prometheus/
    networks:
      - prometheus

  # Grafana
  prometheus_1_grafana:
    image: grafana/grafana:latest
    container_name: prometheus_1_grafana
    restart: unless-stopped
    ports:
      - ${GRAFANA_PORT}:3000
    user: "472"
    volumes:
      - ./prometheus/conf:/etc/prometheus/
    networks:
      - prometheus

  # NGINX
  prometheus_1_nginx:
    build: ./nginx/
    container_name: prometheus_1_nginx
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
    networks:
      - prometheus

  # nginx-prometheus-exporter
  prometheus_1_nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: prometheus_1_nginx_exporter
    restart: unless-stopped
    ports:
      - ${NGINX_PROM_EXPORTER_PORT}:9113
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
    environment:
      TIMEOUT: ${NGINX_PROM_EXPORTER_INTERVAL}
      NGINX_RETRIES: ${NGINX_PROM_EXPORTER_RETRY}
      NGINX_RETRY_INTERVAL: ${NGINX_PROM_EXPORTER_INTERVAL}
      SCRAPE_URI: "http://prometheus_1_nginx:80/status"
      TELEMETRY_PATH: "/metrics"
    networks:
      - prometheus

networks:
  prometheus:
    driver: bridge
